language: node_js
node_js:
- '4.0'
- '9.0'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: npm
    skip_cleanup: true
    email: tituswormer@gmail.com
    api_key:
      secure: Brkd49iBmk618f1dbM9E4ybQDJVCSFLophV5KriMlwW7fXYqtl/6uuIgowWmUq/IiLATrBzG4CAQ5CJl/xOJD+DDPqliNVu6ypAsoDtK6e9Kx8zw8rf8U8sK2znPIyTAawd7NSDLjywXPqFJSxafzZVZq/FJhR96JMZx0vbO0zkzo5eVZ+wjmi2OqeIS3F8MqAO+h3GAwP7RWrNwwNyvQ8mmpzlb5QZgfkIoGTTx7CDLOIdZHJsPkcfyEAn2Z1lHqlI6RmAVL+EFA0P/JqyDk9nMhcVc+AnDvRucjI2vEZAaDEB5aB7I8Mz8W3084B6/c9wPgR4ZhyooFaffVjTYhtcC6GMGGu0AZw2oWCb+3/6f+GuC1LymAZ/GU9fpl2dj6h5bPaTpAyqIOsOJAkhWhd0cw2ntERcFCwaKQMvQmBK9RlFfY7Jxz5g5/JiwdbqVTmsBtMt74Rr0m624Lnd2cLSwiR26gLeWnWQFSvJgL7tGP4fD+qGWVL1b/WZ2ljPxYE7DukBix55/b7LKtONL4TiXnLDs0+uczmSLsmDjEhzcBVHyg0Q204m87ugyJ4miaLbVu+ceAvRejgW4/VXUHet7ECt5UIK6xdU8PQ01rJ4ku75F8sPJtarXlB/Na8PglDNlUkdkZuvvah1L0sCYcmFxW95aAxori36gL4PbaEU=
    on:
      tags: true
      node: '9.0'
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: d6wK/iU24MyfpUMVhA/jTLFRQbSdresF5/Y/poAlcg9Wrd2NIEYnO5ReEgN9N6bAlqE6VM6fBjopP4v2Ack3xgX51B5tf5Znwb8fCitVnL5USwSDsVyuvBC2/CERNH6hBLOW5xU5zO1N6zhu22YoqyY22jpIqeXbNr1nKP3gaE57zK0Oj8+HpBHs/mwnzireZmXuVxA9RXb877B7sACZVOi4UEhWhT5Z+oqrxQ7lXdxPb7In3jRyPPtsLRRH+szJadvZG8/TByUPskFfGP8rrk2dE9Ycr00D/DeJpGWZPFb/LuFKltPZCB0s5yRffMN1Oxtmi/M4+vdMATi2pBCs2hRz1S4wZW1OcxaMdhuDltPqlxiMpOPPeKRxcMYuBH0nyrf8ke8B/fEJoG7wYi3euEFsxBtp7tQ40JFsYTN2D7HE4SYTQ0TpQfLK+Nv9WcDnGOtgtmqDBVpqv/f+jA3yL7b5/YZINdu4u+/TVS0CP94y7JzGQFc9f8IpyyWCk7AwNaiMWgpNZRTfBiQUnEPN5iNEe67TmT1PzQqofHoEYQVXTvDc23FfJEdwqvECuHJOsuWpApTavidMfaqC2KHwJI5eI6dlAOF8uq1gFgBqNU3mI73hdtrR6Nwx/2ehyuNtQt6JlBQMMtxvJCA8UNlHqJULbrCjTmwWUIC+KtphS04=
    file:
      - "nspell.js"
      - "nspell.min.js"
    on:
      tags: true
      node: '9.0'
