language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: d6wK/iU24MyfpUMVhA/jTLFRQbSdresF5/Y/poAlcg9Wrd2NIEYnO5ReEgN9N6bAlqE6VM6fBjopP4v2Ack3xgX51B5tf5Znwb8fCitVnL5USwSDsVyuvBC2/CERNH6hBLOW5xU5zO1N6zhu22YoqyY22jpIqeXbNr1nKP3gaE57zK0Oj8+HpBHs/mwnzireZmXuVxA9RXb877B7sACZVOi4UEhWhT5Z+oqrxQ7lXdxPb7In3jRyPPtsLRRH+szJadvZG8/TByUPskFfGP8rrk2dE9Ycr00D/DeJpGWZPFb/LuFKltPZCB0s5yRffMN1Oxtmi/M4+vdMATi2pBCs2hRz1S4wZW1OcxaMdhuDltPqlxiMpOPPeKRxcMYuBH0nyrf8ke8B/fEJoG7wYi3euEFsxBtp7tQ40JFsYTN2D7HE4SYTQ0TpQfLK+Nv9WcDnGOtgtmqDBVpqv/f+jA3yL7b5/YZINdu4u+/TVS0CP94y7JzGQFc9f8IpyyWCk7AwNaiMWgpNZRTfBiQUnEPN5iNEe67TmT1PzQqofHoEYQVXTvDc23FfJEdwqvECuHJOsuWpApTavidMfaqC2KHwJI5eI6dlAOF8uq1gFgBqNU3mI73hdtrR6Nwx/2ehyuNtQt6JlBQMMtxvJCA8UNlHqJULbrCjTmwWUIC+KtphS04=
  file:
    - 'nspell.js'
    - 'nspell.min.js'
  on:
    tags: true
